Add first version of amtrak script
sverch/amtrakomatic pull request #1
Opened 2019-07-15 02:48 UTC by sverch

This has two modes:

- Read specific trips including train numbers from a CSV to add them up
- Dump all results for a single search query

See README for usage.

2019-07-15 03:48 UTC, SYU15 commented
Nice!

2019-07-15 12:30 UTC, jisaacso requested changes
Only you would go so far _off the rails_ . Overall looks good.

2019-07-15 12:30 UTC, jisaacso commented on amtrakomatic/do_all_searches.sh
> +#run python main.py --source NewYork --destination Boston --date  08/11/2019
all the comments

2019-07-15 12:30 UTC, jisaacso commented on amtrakomatic/extract_expected_result.sh
> +    Runs pytest and vomits the json of the expected output for whatever failed.
I would suggest a real test runner, e.g., tox

2019-07-15 12:30 UTC, jisaacso commented on amtrakomatic/fixup.sh
> +echo '[]' >| test_data/seattle_chicago_08_24_2019_False_0.json
why?

2019-07-15 12:30 UTC, jisaacso commented on amtrakomatic/format_output.py
> +def print_result(result):
more descriptive name?

2019-07-15 12:30 UTC, jisaacso commented on amtrakomatic/fuzzy_match.py
> +    station_map = load_stations()
calls load for every search?

2019-07-17 00:44 UTC, sverch commented
I've trained my whole life for this moment @jisaacso...

2019-07-20 02:41 UTC, merged